sudo: false
language: node_js
node_js:
    - "node"
jobs:
    include:
        - script: COVERALLS_FLAG_NAME=run-coveralls nyc npm run test && nyc report --reporter=text-lcov | coveralls
notifications:
    webhooks: https://coveralls.io/webhook
